from designer.base import (ScrollArea, QLabel, QFrame, QVBoxLayout, QPushButton, QHBoxLayout, QTableWidget,
                           QAbstractItemView)
from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import *

class ChooseChr(ScrollArea):
    def __init__(self, parent=None):
        super(ChooseChr, self).__init__()
        self.parent = parent
        self.chrShow_widget = QWidget()
        self.setWidget(self.chrShow_widget)
        self.setWidgetResizable(True)
        self.setObjectName("chrShow")
        with open("QSS/chooseChr.qss", 'r', encoding='utf-8') as f:
            self.style = f.read()
            self.setStyleSheet(self.style)
            self.chrShow_widget.setStyleSheet(self.style)
        self.setLabels()
        self.setLayouts()

    def setLabels(self):
        self.chr1=QToolButton()
        self.chr1.setText("1号染色体")
        self.chr1.setIcon(QtGui.QIcon("resource/1.png"))
        self.chr1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr1.setObjectName("chrButton")
        self.chr2 = QToolButton()
        self.chr2.setText("2号染色体")
        self.chr2.setIcon(QtGui.QIcon("resource/2.png"))
        self.chr2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr2.setObjectName("chrButton")
        self.chr3 = QToolButton()
        self.chr3.setText("3号染色体")
        self.chr3.setIcon(QtGui.QIcon("resource/3.png"))
        self.chr3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr3.setObjectName("chrButton")
        self.chr4 = QToolButton()
        self.chr4.setText("4号染色体")
        self.chr4.setIcon(QtGui.QIcon("resource/4.png"))
        self.chr4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr4.setObjectName("chrButton")
        self.chr5 = QToolButton()
        self.chr5.setText("5号染色体")
        self.chr5.setIcon(QtGui.QIcon("resource/5.png"))
        self.chr5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr5.setObjectName("chrButton")
        self.chr6 = QToolButton()
        self.chr6.setText("6号染色体")
        self.chr6.setIcon(QtGui.QIcon("resource/6.png"))
        self.chr6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr6.setObjectName("chrButton")
        self.chr7 = QToolButton()
        self.chr7.setText("7号染色体")
        self.chr7.setIcon(QtGui.QIcon("resource/7.png"))
        self.chr7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr7.setObjectName("chrButton")
        self.chr8 = QToolButton()
        self.chr8.setText("8号染色体")
        self.chr8.setIcon(QtGui.QIcon("resource/8.png"))
        self.chr8.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr8.setObjectName("chrButton")
        self.chr9 = QToolButton()
        self.chr9.setText("9号染色体")
        self.chr9.setIcon(QtGui.QIcon("resource/9.png"))
        self.chr9.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr9.setObjectName("chrButton")
        self.chr10 = QToolButton()
        self.chr10.setText("10号染色体")
        self.chr10.setIcon(QtGui.QIcon("resource/10.png"))
        self.chr10.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr10.setObjectName("chrButton")
        self.chr11 = QToolButton()
        self.chr11.setText("11号染色体")
        self.chr11.setIcon(QtGui.QIcon("resource/11.png"))
        self.chr11.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr11.setObjectName("chrButton")
        self.chr12 = QToolButton()
        self.chr12.setText("12号染色体")
        self.chr12.setIcon(QtGui.QIcon("resource/12.png"))
        self.chr12.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr12.setObjectName("chrButton")
        self.chr13 = QToolButton()
        self.chr13.setText("13号染色体")
        self.chr13.setIcon(QtGui.QIcon("resource/13.png"))
        self.chr13.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr13.setObjectName("chrButton")
        self.chr14 = QToolButton()
        self.chr14.setText("14号染色体")
        self.chr14.setIcon(QtGui.QIcon("resource/14.png"))
        self.chr14.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr14.setObjectName("chrButton")
        self.chr15 = QToolButton()
        self.chr15.setText("15号染色体")
        self.chr15.setIcon(QtGui.QIcon("resource/15.png"))
        self.chr15.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr15.setObjectName("chrButton")
        self.chr16 = QToolButton()
        self.chr16.setText("16号染色体")
        self.chr16.setIcon(QtGui.QIcon("resource/16.png"))
        self.chr16.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr16.setObjectName("chrButton")
        self.chr17 = QToolButton()
        self.chr17.setText("17号染色体")
        self.chr17.setIcon(QtGui.QIcon("resource/17.png"))
        self.chr17.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr17.setObjectName("chrButton")
        self.chr18 = QToolButton()
        self.chr18.setText("18号染色体")
        self.chr18.setIcon(QtGui.QIcon("resource/18.png"))
        self.chr18.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr18.setObjectName("chrButton")
        self.chr19 = QToolButton()
        self.chr19.setText("19号染色体")
        self.chr19.setIcon(QtGui.QIcon("resource/19.png"))
        self.chr19.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr19.setObjectName("chrButton")
        self.chr20 = QToolButton()
        self.chr20.setText("20号染色体")
        self.chr20.setIcon(QtGui.QIcon("resource/20.png"))
        self.chr20.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr20.setObjectName("chrButton")
        self.chr21 = QToolButton()
        self.chr21.setText("21号染色体")
        self.chr21.setIcon(QtGui.QIcon("resource/21.png"))
        self.chr21.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr21.setObjectName("chrButton")
        self.chr22 = QToolButton()
        self.chr22.setText("22号染色体")
        self.chr22.setIcon(QtGui.QIcon("resource/22.png"))
        self.chr22.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chr22.setObjectName("chrButton")
        self.chrX = QToolButton()
        self.chrX.setText("X染色体")
        self.chrX.setIcon(QtGui.QIcon("resource/X.png"))
        self.chrX.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chrX.setObjectName("chrButton")
        self.chrY = QToolButton()
        self.chrY.setText("Y染色体")
        self.chrY.setIcon(QtGui.QIcon("resource/Y.png"))
        self.chrY.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.chrY.setObjectName("chrButton")

        self.chr1.setIconSize(QtCore.QSize(50, 80))
        self.chr2.setIconSize(QtCore.QSize(50, 80))
        self.chr3.setIconSize(QtCore.QSize(50, 80))
        self.chr4.setIconSize(QtCore.QSize(50, 80))
        self.chr5.setIconSize(QtCore.QSize(50, 80))
        self.chr6.setIconSize(QtCore.QSize(50, 80))
        self.chr7.setIconSize(QtCore.QSize(50, 80))
        self.chr8.setIconSize(QtCore.QSize(50, 80))
        self.chr9.setIconSize(QtCore.QSize(50, 80))
        self.chr10.setIconSize(QtCore.QSize(50, 80))
        self.chr11.setIconSize(QtCore.QSize(50, 80))
        self.chr12.setIconSize(QtCore.QSize(50, 80))
        self.chr13.setIconSize(QtCore.QSize(50, 80))
        self.chr14.setIconSize(QtCore.QSize(50, 80))
        self.chr15.setIconSize(QtCore.QSize(50, 80))
        self.chr16.setIconSize(QtCore.QSize(50, 80))
        self.chr17.setIconSize(QtCore.QSize(50, 80))
        self.chr18.setIconSize(QtCore.QSize(50, 80))
        self.chr19.setIconSize(QtCore.QSize(50, 80))
        self.chr20.setIconSize(QtCore.QSize(50, 80))
        self.chr21.setIconSize(QtCore.QSize(50, 80))
        self.chr22.setIconSize(QtCore.QSize(50, 80))
        self.chrX.setIconSize(QtCore.QSize(50, 80))
        self.chrY.setIconSize(QtCore.QSize(50, 80))

    def setLayouts(self):
        self.mainLayout = QGridLayout(self.chrShow_widget)
        self.chr_layout = QGridLayout()
        self.chr_widget = QWidget()
        self.chr_widget.setLayout(self.chr_layout)
        self.chr_layout.addWidget(self.chr1,0,0,1,1)
        self.chr_layout.addWidget(self.chr2, 0, 1, 1, 1)
        self.chr_layout.addWidget(self.chr3, 0, 2, 1, 1)
        self.chr_layout.addWidget(self.chr4, 0, 3, 1, 1)
        self.chr_layout.addWidget(self.chr5, 0, 4, 1, 1)
        self.chr_layout.addWidget(self.chr6, 0, 5, 1, 1)
        self.chr_layout.addWidget(self.chr7, 1, 0, 1, 1)
        self.chr_layout.addWidget(self.chr8, 1, 1, 1, 1)
        self.chr_layout.addWidget(self.chr9, 1, 2, 1, 1)
        self.chr_layout.addWidget(self.chr10, 1, 3, 1, 1)
        self.chr_layout.addWidget(self.chr11, 1, 4, 1, 1)
        self.chr_layout.addWidget(self.chr12, 1, 5, 1, 1)
        self.chr_layout.addWidget(self.chr13, 2, 0, 1, 1)
        self.chr_layout.addWidget(self.chr14, 2, 1, 1, 1)
        self.chr_layout.addWidget(self.chr15, 2, 2, 1, 1)
        self.chr_layout.addWidget(self.chr16, 2, 3, 1, 1)
        self.chr_layout.addWidget(self.chr17, 2, 4, 1, 1)
        self.chr_layout.addWidget(self.chr18, 2, 5, 1, 1)
        self.chr_layout.addWidget(self.chr19, 3, 0, 1, 1)
        self.chr_layout.addWidget(self.chr20, 3, 1, 1, 1)
        self.chr_layout.addWidget(self.chr21, 3, 2, 1, 1)
        self.chr_layout.addWidget(self.chr22, 3, 3, 1, 1)
        self.chr_layout.addWidget(self.chrX, 3, 4, 1, 1)
        self.chr_layout.addWidget(self.chrY, 3, 5, 1, 1)

        self.mainLayout.addWidget(self.chr_widget, 1, 1, 4, 9)